      File "/opt/conda/conda-bld/numpy_and_dev_1530448912024/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
        self.test(*self.arg)
      File "/opt/conda/conda-bld/numpy_and_dev_1530448912024/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/python2.7/site-packages/numpy/core/tests/test_print.py", line 114, in _check_complex_inf_nan
        assert_equal(str(dtype(c)), s)
      File "/opt/conda/conda-bld/numpy_and_dev_1530448912024/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/python2.7/site-packages/numpy/testing/nose_tools/utils.py", line 411, in assert_equal
        raise AssertionError(msg)
    AssertionError:
    Items are not equal:
     ACTUAL: '(inf1.j)'
     DESIRED: '(inf+1j)'
    ======================================================================
    FAIL: Check inf/nan formatting of complex types.
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/opt/conda/conda-bld/numpy_and_dev_1530448912024/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
        self.test(*self.arg)
      File "/opt/conda/conda-bld/numpy_and_dev_1530448912024/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/python2.7/site-packages/numpy/core/tests/test_print.py", line 114, in _check_complex_inf_nan
        assert_equal(str(dtype(c)), s)
      File "/opt/conda/conda-bld/numpy_and_dev_1530448912024/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/python2.7/site-packages/numpy/testing/nose_tools/utils.py", line 411, in assert_equal
        raise AssertionError(msg)
    AssertionError:
    Items are not equal:
     ACTUAL: '(nan1.j)'
     DESIRED: '(nan+1j)'
    ======================================================================
    FAIL: Check inf/nan formatting of complex types.
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/opt/conda/conda-bld/numpy_and_dev_1530448912024/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
        self.test(*self.arg)
      File "/opt/conda/conda-bld/numpy_and_dev_1530448912024/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/python2.7/site-packages/numpy/core/tests/test_print.py", line 114, in _check_complex_inf_nan
        assert_equal(str(dtype(c)), s)
      File "/opt/conda/conda-bld/numpy_and_dev_1530448912024/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/python2.7/site-packages/numpy/testing/nose_tools/utils.py", line 411, in assert_equal
        raise AssertionError(msg)
    AssertionError:
    Items are not equal:
     ACTUAL: '(1.+nanj)'
     DESIRED: '(1+nanj)'
    ======================================================================
    FAIL: Check inf/nan formatting of complex types.
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/opt/conda/conda-bld/numpy_and_dev_1530448912024/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
        self.test(*self.arg)
      File "/opt/conda/conda-bld/numpy_and_dev_1530448912024/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/python2.7/site-packages/numpy/core/tests/test_print.py", line 114, in _check_complex_inf_nan
        assert_equal(str(dtype(c)), s)
      File "/opt/conda/conda-bld/numpy_and_dev_1530448912024/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/python2.7/site-packages/numpy/testing/nose_tools/utils.py", line 411, in assert_equal
        raise AssertionError(msg)
    AssertionError:
    Items are not equal:
     ACTUAL: '(-inf1.j)'
     DESIRED: '(-inf+1j)'
    ======================================================================
    FAIL: Check inf/nan formatting of complex types.
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/opt/conda/conda-bld/numpy_and_dev_1530448912024/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
        self.test(*self.arg)
      File "/opt/conda/conda-bld/numpy_and_dev_1530448912024/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/python2.7/site-packages/numpy/core/tests/test_print.py", line 114, in _check_complex_inf_nan
        assert_equal(str(dtype(c)), s)
      File "/opt/conda/conda-bld/numpy_and_dev_1530448912024/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/python2.7/site-packages/numpy/testing/nose_tools/utils.py", line 411, in assert_equal
        raise AssertionError(msg)
    AssertionError:
    Items are not equal:
     ACTUAL: '-nanj'
     DESIRED: 'nanj'
    ======================================================================
    FAIL: Check formatting when using print
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/opt/conda/conda-bld/numpy_and_dev_1530448912024/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
        self.test(*self.arg)
      File "/opt/conda/conda-bld/numpy_and_dev_1530448912024/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/python2.7/site-packages/numpy/core/tests/test_print.py", line 137, in check_float_type_print
        _test_redirected_print(float(x), tp)
      File "/opt/conda/conda-bld/numpy_and_dev_1530448912024/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/python2.7/site-packages/numpy/core/tests/test_print.py", line 133, in _test_redirected_print
        err_msg='print failed for type%s' % tp)
      File "/opt/conda/conda-bld/numpy_and_dev_1530448912024/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/python2.7/site-packages/numpy/testing/nose_tools/utils.py", line 411, in assert_equal
        raise AssertionError(msg)
    AssertionError:
    Items are not equal: print failed for type
     ACTUAL: '0.0\n'
     DESIRED: '0.\n'
    ======================================================================
    FAIL: Check formatting when using print
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/opt/conda/conda-bld/numpy_and_dev_1530448912024/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
        self.test(*self.arg)
      File "/opt/conda/conda-bld/numpy_and_dev_1530448912024/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/python2.7/site-packages/numpy/core/tests/test_print.py", line 152, in check_complex_type_print
        _test_redirected_print(complex(x), tp)
      File "/opt/conda/conda-bld/numpy_and_dev_1530448912024/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/python2.7/site-packages/numpy/core/tests/test_print.py", line 133, in _test_redirected_print
        err_msg='print failed for type%s' % tp)
      File "/opt/conda/conda-bld/numpy_and_dev_1530448912024/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/python2.7/site-packages/numpy/testing/nose_tools/utils.py", line 411, in assert_equal
        raise AssertionError(msg)
    AssertionError:
    Items are not equal: print failed for type
     ACTUAL: '0j\n'
     DESIRED: '0.j\n'
    ======================================================================
    FAIL: numpy.core.tests.test_print.test_locale_longdouble
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/opt/conda/conda-bld/numpy_and_dev_1530448912024/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
        self.test(*self.arg)
      File "/opt/conda/conda-bld/numpy_and_dev_1530448912024/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/python2.7/site-packages/numpy/core/tests/test_print.py", line 228, in wrapper
        return func(*args, **kwargs)
      File "/opt/conda/conda-bld/numpy_and_dev_1530448912024/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/python2.7/site-packages/numpy/core/tests/test_print.py", line 243, in test_locale_longdouble
        assert_equal(str(np.longdouble('1.2')), str(float(1.2)))
      File "/opt/conda/conda-bld/numpy_and_dev_1530448912024/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/python2.7/site-packages/numpy/testing/nose_tools/utils.py", line 411, in assert_equal
        raise AssertionError(msg)
    AssertionError:
    Items are not equal:
     ACTUAL: '1,2'
     DESIRED: '1.2'
    ======================================================================
    FAIL: numpy.core.tests.test_scalarprint.TestRealScalars.test_dragon4_interface
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/opt/conda/conda-bld/numpy_and_dev_1530448912024/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
        self.test(*self.arg)
      File "/opt/conda/conda-bld/numpy_and_dev_1530448912024/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/python2.7/site-packages/numpy/core/tests/test_scalarprint.py", line 218, in test_dragon4_interface
        assert_equal(fpos(tp('1.0'), pad_left=4, pad_right=4), "   1.    ")
      File "/opt/conda/conda-bld/numpy_and_dev_1530448912024/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/python2.7/site-packages/numpy/testing/nose_tools/utils.py", line 411, in assert_equal
        raise AssertionError(msg)
    AssertionError:
    Items are not equal:
     ACTUAL: '1.'
     DESIRED: '   1.    '
    ======================================================================
    FAIL: numpy.core.tests.test_scalarprint.TestRealScalars.test_str
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/opt/conda/conda-bld/numpy_and_dev_1530448912024/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
        self.test(*self.arg)
      File "/opt/conda/conda-bld/numpy_and_dev_1530448912024/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/python2.7/site-packages/numpy/core/tests/test_scalarprint.py", line 30, in test_str
        assert_equal(str(styp(val)), want, err_msg=msg)
      File "/opt/conda/conda-bld/numpy_and_dev_1530448912024/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/python2.7/site-packages/numpy/testing/nose_tools/utils.py", line 411, in assert_equal
        raise AssertionError(msg)
    AssertionError:
    Items are not equal: for str(float128(0.0))
     ACTUAL: '0.'
     DESIRED: '0.0'
    ======================================================================
    FAIL: numpy.core.tests.test_umath.TestComplexFunctions.test_loss_of_precision_longcomplex
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/opt/conda/conda-bld/numpy_and_dev_1530448912024/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
        self.test(*self.arg)
      File "/opt/conda/conda-bld/numpy_and_dev_1530448912024/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/python2.7/site-packages/numpy/testing/nose_tools/decorators.py", line 217, in knownfailer
        return f(*args, **kwargs)
      File "/opt/conda/conda-bld/numpy_and_dev_1530448912024/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/python2.7/site-packages/numpy/core/tests/test_umath.py", line 2398, in test_loss_of_precision_longcomplex
        self.check_loss_of_precision(np.longcomplex)
      File "/opt/conda/conda-bld/numpy_and_dev_1530448912024/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/python2.7/site-packages/numpy/core/tests/test_umath.py", line 2349, in check_loss_of_precision
        check(x_series, 50*eps)
      File "/opt/conda/conda-bld/numpy_and_dev_1530448912024/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/python2.7/site-packages/numpy/core/tests/test_umath.py", line 2322, in check
        'arcsinh'))
      File "/opt/conda/conda-bld/numpy_and_dev_1530448912024/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/python2.7/site-packages/numpy/testing/nose_tools/utils.py", line 93, in assert_
        raise AssertionError(smsg)
    AssertionError: (131, 1.549874e-09, 4.003517e-19, 'arcsinh')
    ----------------------------------------------------------------------